name: test build process

on:
  push:
    branches: [ main, check_build1 ]
  pull_request:
    branches: [ main ]

jobs:
  jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolset: gcc-9
            cxxstd: "14,17"
            os: ubuntu-20.04
            install: g++-9

  build:

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Prepare llvm build directory name
        id: llvm-build-dir
        run: |
          echo "::set-output name=commit::$(git submodule status | awk '{print $1;}')"
      - name: Cache llvm build directory
        uses: actions/cache@v3
        with:
          path: llvm
          key: build-${{ steps.llvm-build-dir.outputs.commit }}
      - name: Test build
        run: bash ./tests/Actions/TestBuild.sh  llvm/build-${{ steps.llvm-build-dir.outputs.commit }}
